---
development:
  dialect: mysql
  database: test
  user: root
  password: 123456
  host: 127.0.0.1
  pool: 3306

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/crud_demo_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/crud_demo_production?sslmode=disable"}}
